### ISSUE TITLE
Unble to run windows container version 1809 

### ISSUE THREAD

**Issue by raymak23** [MicrosoftDocs/Virtualization-Documentation#1030]
Hi everyone,

I am opening this issue based upon this [documentation](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems): 

I joined windows server 2019 datacenter edition to my Kubernetes 1.14 version cluster and I am getting below error when I deploy it from [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/deploying-resources):

```
Normal   SandboxChanged          22s (x12 over 41s)  kubelet, win-uq3cdgb5r7g  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  21s (x4 over 26s)   kubelet, win-uq3cdgb5r7g  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "win-webserver-cfcdfb59b-xdn2z": Error response from daemon: CreateComputeSystem cf6b9017d28776bdcf852cad3e25b2b296a60b8729d82397046f1279212ea00f: The container operating system does not match the host operating system.
(extra info: {"SystemType":"Container","Name":"cf6b9017d28776bdcf852cad3e25b2b296a60b8729d82397046f1279212ea00f","Owner":"docker","VolumePath":"\\\\?\\Volume{d03ade10-14ef-4486-aa63-406f2a7e5048}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\cf6b9017d28776bdcf852cad3e25b2b296a60b8729d82397046f1279212ea00f","Layers":[{"ID":"7cf9a822-5cb5-5380-98c3-99885c3639f8","Path":"C:\\ProgramData\\docker\\windowsfilter\\83e740543f7683c25c7880388dbe2885f32250e927ab0f2119efae9f68da5178"},{"ID":"600d6d6b-8810-5bf3-ad01-06d0ba1f97a4","Path":"C:\\ProgramData\\docker\\windowsfilter\\529e04c75d56f948819cd62e4886d865d8faac7470be295e7116ddf47ca15251"},{"ID":"f185c0c0-eccf-5ff9-b9fb-2939562b75c3","Path":"C:\\ProgramData\\docker\\windowsfilter\\7640b81c6fff930a838e97c6c793b4fa9360b6505718aa84573999aa41223e80"}],"ProcessorWeight":2,"HostName":"win-webserver-cfcdfb59b-xdn2z","HvPartition":false})
```

Any idea what I am missing? Below is my node status:

```
PS C:\k> .\kubectl.exe get nodes -o wide
NAME                STATUS     ROLES    AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION               CONTAINER-RUNTIME
k8s-master-node     Ready      master   40h    v1.14.0   192.168.0.120   <none>        CentOS Linux 7 (Core)            3.10.0-957.10.1.el7.x86_64   docker://1.13.1
k8s-worker-node-1   Ready      <none>   40h    v1.14.0   192.168.0.121   <none>        CentOS Linux 7 (Core)            3.10.0-957.10.1.el7.x86_64   docker://1.13.1
win-uq3cdgb5r7g     Ready      <none>   5h5m   v1.14.0   192.168.0.123   <none>        Windows Server 2019 Datacenter   10.0.17763.379               docker://18.9.4
PS C:\k>
```

And my pods

```
PS C:\k> .\kubectl.exe get pods -A -o wide
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE   IP              NODE                NOMINATED NODE   READINESS GATES
default       win-webserver-cfcdfb59b-xdn2z             0/1     ContainerCreating   0          22m   <none>          win-uq3cdgb5r7g     <none>           <none>
default       win-webserver-cfcdfb59b-xfb75             0/1     ContainerCreating   0          22m   <none>          win-uq3cdgb5r7g     <none>           <none>
kube-system   coredns-fb8b8dccf-9jd8r                   1/1     Running             22         40h   10.244.1.11     k8s-worker-node-1   <none>           <none>
kube-system   coredns-fb8b8dccf-kfjsz                   1/1     Running             22         40h   10.244.1.9      k8s-worker-node-1   <none>           <none>
kube-system   etcd-k8s-master-node                      1/1     Running             1          40h   192.168.0.120   k8s-master-node     <none>           <none>
kube-system   kube-apiserver-k8s-master-node            1/1     Running             1          40h   192.168.0.120   k8s-master-node     <none>           <none>
kube-system   kube-controller-manager-k8s-master-node   1/1     Running             1          40h   192.168.0.120   k8s-master-node     <none>           <none>
kube-system   kube-flannel-ds-amd64-4clxz               1/1     Running             1          21h   192.168.0.120   k8s-master-node     <none>           <none>
kube-system   kube-flannel-ds-amd64-fjqxp               1/1     Running             3          21h   192.168.0.121   k8s-worker-node-1   <none>           <none>
kube-system   kube-proxy-qln5d                          1/1     Running             1          20h   192.168.0.120   k8s-master-node     <none>           <none>
kube-system   kube-proxy-thctm                          1/1     Running             1          20h   192.168.0.121   k8s-worker-node-1   <none>           <none>
kube-system   kube-scheduler-k8s-master-node            1/1     Running             1          40h   192.168.0.120   k8s-master-node     <none>           <none>
kube-system   kubernetes-dashboard-5f7b999d65-kchnp     1/1     Running             1          20h   10.244.1.10     k8s-worker-node-1   <none>           <none>
```

Here is the `yaml` deployment I tried:

```
apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  labels:
    app: win-webserver
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: win-webserver
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      containers:
      - name: windowswebserver
        image: mcr.microsoft.com/windows/servercore:1809
        command:
        - powershell.exe
        - -command
        - "<#code used from https://gist.github.com/wagnerandrade/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/') ; $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAddress); $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$ip[1].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
      nodeSelector:
        beta.kubernetes.io/os: windows
```
