### ISSUE TITLE
How do you modify version of pause container to proper version?

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/Virtualization-Documentation#1360]
I have 1909 host and trying to deploy 1909 image on it but it goes into restart loop due to OS mismatch. My POD has only reference to my container but not pause container which I assume is being handled by underlying kubernetes control plane. So how do I properly deploy POD based on latest version of OS. My POD spec is below which works fine if I run pod manually via `docker` commands but fails as K8 pod
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: win-webserver
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      containers:
      - command:
        - powershell.exe
        - -command
        - while ($true) { "[{0}] [{2}] {1}" -f (Get-Date),(Get-Random),$env:COMPUTERNAME;
          Start-Sleep 5}
        image: mcr.microsoft.com/windows/servercore:1909
        imagePullPolicy: IfNotPresent
        name: windowswebserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        beta.kubernetes.io/os: windows
      restartPolicy: Always
status: {}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d162332-10db-b9f2-92cc-19475ca448ed
* Version Independent ID: 82e7e978-51d0-e563-87bf-e0c82c2bb04a
* Content: [Troubleshooting Kubernetes](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems)
* Content Source: [virtualization/windowscontainers/kubernetes/common-problems.md](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/kubernetes/common-problems.md)
* Product: **containers**
* GitHub Login: @gkudra-msft
* Microsoft Alias: **gekudray**
